import streamlit as st
from datetime import datetime

def generate_report(evaluation, responses):
    """Generate downloadable text report"""
    report = f"""
AI INTERVIEW REPORT
==================
Candidate: {st.session_state.candidate_name}
Position: Software Development Engineer Intern
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

OVERALL PERFORMANCE
==================
Overall Score: {evaluation.get('overall_score', 0)}/100
Recommendation: {evaluation.get('recommendation', 'Under Review')}

DETAILED SCORES
==============
Technical Knowledge: {evaluation.get('technical_score', 0)}/100
Communication: {evaluation.get('communication_score', 0)}/100
Problem Solving: {evaluation.get('problem_solving_score', 0)}/100
Behavioral Fit: {evaluation.get('behavioral_score', 0)}/100

STRENGTHS
=========
{chr(10).join('• ' + s for s in evaluation.get('strengths', []))}

IMPROVEMENT AREAS
================
{chr(10).join('• ' + i for i in evaluation.get('improvements', []))}

DETAILED FEEDBACK
================
{evaluation.get('detailed_feedback', 'No detailed feedback available.')}

QUESTION RESPONSES
=================
"""
    
    for i, response in enumerate(responses, 1):
        report += f"""
Question {i}: {response.category}
{'-' * 50}
Q: {response.question}
A: {response.answer}
Time: {response.time_taken:.1f} seconds
"""
    
    report += "\n---\nGenerated by AI Interviewer System"
    return report